project_id = "eipwebpvpadugddmepnr"

[functions.process-receipt-ocr]
verify_jwt = true

[functions.send-nurture-email]
verify_jwt = false

[functions.create-tripwire-checkout]
verify_jwt = false

[functions.get-checkout-session]
verify_jwt = false

[functions.wellbie-chat]
verify_jwt = true

[functions.plaid-create-link-token]
verify_jwt = true

[functions.plaid-exchange-token]
verify_jwt = true

[functions.plaid-sync-transactions]
verify_jwt = true

[functions.sync-npi-data]
verify_jwt = true
